### ISSUE TITLE
Does not compile on Ubuntu/aarch64

### ISSUE THREAD

**Issue by stroetgen** [backuppc/rsync-bpc#17]
Rsync-bpc does not compile on Ubuntu 20.04.1 on Raspberry Pi 4 Model B. Seems to have an ACL problem. 

`Linux backup 5.4.0-1019-raspi #21-Ubuntu SMP PREEMPT Mon Sep 14 07:20:34 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux`

`./configure --disable-acl-support` does not help.

```
...
checking for _acl... no
checking for __acl... no
checking for _facl... no
checking for __facl... no
checking whether to support ACLs... no
...
```

```
gcc -I. -I. -g -O2 -DHAVE_CONFIG_H -Wall -W -Wno-unused-parameter  -c lib/sysacls.c -o lib/sysacls.o
lib/sysacls.c:2761:2: error: #error No ACL functions defined for this platform!
 2761 | #error No ACL functions defined for this platform!
      |  ^~~~~
make: *** [Makefile:65: lib/sysacls.o] Error 1
```

It compiles (and works!) after removing "lib/sysacls.o" from LIBOBJ in Makefile.

**Comment by craigbarratt** [comment]
See #13 - if you build from source you need to install `libacl1-dev`, and re-run `configure`.

**Comment by stroetgen** [comment]
It's already installed:

```
apt-get install libacl1-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libacl1-dev is already the newest version (2.2.53-6).
```

**Comment by craigbarratt** [comment]
Ok.  Does the underlying OS actually support ACLs?  What's the output from
```
egrep ACL config.h
```

`rsync-bpc` doesn't actually use the ACL code.  It's possible a reasonable fix, similar to just removing `lib/sysacls.o` from the `Makefile` is to add:
```
#define HAVE_POSIX_ACLS 1
```
to `rsync.h`.

**Comment by craigbarratt** [comment]
Can you confirm that adding that define to `rsync.h` solves your build problem?

**Comment by stroetgen** [comment]
ACL is supported.

```
root@backup:/tmp# touch test
root@backup:/tmp# getfacl test
# file: test
# owner: root
# group: root
user::rw-
group::r--
other::r--

root@backup:/tmp# setfacl -m u:backuppc:rw test
root@backup:/tmp# getfacl test
# file: test
# owner: root
# group: root
user::rw-
user:backuppc:rw-
group::r--
mask::rw-
other::r--
```

`config.h` after `./configure --disable-acl-support`:

```
egrep ACL config.h
/* #undef HAVE_ACLSORT */
/* #undef HAVE_ACL_GET_PERM_NP */
#define HAVE_ACL_LIBACL_H 1
/* true if you have AIX ACLs */
/* #undef HAVE_AIX_ACLS */
/* true if you have HPUX ACLs */
/* #undef HAVE_HPUX_ACLS */
/* true if you have IRIX ACLs */
/* #undef HAVE_IRIX_ACLS */
/* #undef HAVE_LIBACL */
/* true if you have Mac OS X ACLs */
/* #undef HAVE_OSX_ACLS */
/* true if you have posix ACLs */
/* #undef HAVE_POSIX_ACLS */
/* true if you have solaris ACLs */
/* #undef HAVE_SOLARIS_ACLS */
#define HAVE_SYS_ACL_H 1
/* true if you have Tru64 ACLs */
/* #undef HAVE_TRU64_ACLS */
/* true if you have UnixWare ACLs */
/* #undef HAVE_UNIXWARE_ACLS */
/* #undef HAVE__ACL */
/* #undef HAVE__FACL */
/* #undef HAVE___ACL */
/* #undef HAVE___FACL */
/* Define to 1 to add support for ACLs */
/* #undef SUPPORT_ACLS */
```

`config.h` after `./configure` without `--disable-acl-support`:

```
/* #undef HAVE_ACLSORT */
/* #undef HAVE_ACL_GET_PERM_NP */
#define HAVE_ACL_LIBACL_H 1
/* true if you have AIX ACLs */
/* #undef HAVE_AIX_ACLS */
/* true if you have HPUX ACLs */
/* #undef HAVE_HPUX_ACLS */
/* true if you have IRIX ACLs */
/* #undef HAVE_IRIX_ACLS */
#define HAVE_LIBACL 1
/* true if you have Mac OS X ACLs */
/* #undef HAVE_OSX_ACLS */
/* true if you have posix ACLs */
#define HAVE_POSIX_ACLS 1
/* true if you have solaris ACLs */
/* #undef HAVE_SOLARIS_ACLS */
#define HAVE_SYS_ACL_H 1
/* true if you have Tru64 ACLs */
/* #undef HAVE_TRU64_ACLS */
/* true if you have UnixWare ACLs */
/* #undef HAVE_UNIXWARE_ACLS */
/* #undef HAVE__ACL */
/* #undef HAVE__FACL */
/* #undef HAVE___ACL */
/* #undef HAVE___FACL */
/* Define to 1 to add support for ACLs */
#define SUPPORT_ACLS 1
```

Here I already find `#define HAVE_POSIX_ACLS 1`

Now it builds without problem.

```
./configure
make
make install
```

A few days ago it failed with ACL errors, that's why I used `--disable-acl-support`.

I can't reproduce the error. I close the issue.

Thank's for your support!
